spring:
  datasource:
    url: jdbc:mysql://localhost:10400/example?SCHEMA=example&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1234
    hikari:
      auto-commit: true
      connection-timeout: 30000
      max-lifetime: 30000
      maximum-pool-size: 75
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
